CREATE TABLE price_change_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    asset_id VARCHAR(128) NOT NULL,
    market_id VARCHAR(64),
    condition_id VARCHAR(128),
    market_slug VARCHAR(255),
    market_question VARCHAR(500),
    outcome VARCHAR(64),
    previous_price NUMERIC(19, 8) NOT NULL,
    current_price NUMERIC(19, 8) NOT NULL,
    price_source VARCHAR(32) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_price_change_events_asset_created
    ON price_change_events (asset_id, created_at, id);
